name = "AperiodicSurrogates"
uuid = "b45ef32a-9cdb-40be-815b-79ae4e94a75e"
authors = ["brendanjohnharris <brendanjohnharris@gmail.com> and contributors"]
version = "0.1.0"

[deps]
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
PyFOOOF = "bb993ee8-2a51-46a1-a315-55ff424041b4"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
TimeseriesSurrogates = "c804724b-8c18-5caa-8579-6025a0767c70"

[compat]
TimeseriesSurrogates = "2"
Reexport = "1"
IntervalSets = "0.4 - 0.7"
PyFOOOF = "0.1"
julia = "1.6 - 1.8"
